name: Democracy
main: net.ubudog.democracy.Democracy
version: 0.1

commands:
   vote:
      description: Use this to cast your vote for an active poll.
      usage: /vote <pollid>
   startpoll:
      description: Use this to start a poll on the server.
      usage: /startpoll <pollname> <options>
   stoppoll:
      description: Use this to stop a poll on the server.
      usage: /stoppoll <pollname> 
   democracy:
      description: Use this to view Democracy's version, command info, and more.
      usage: /democracy
   pollstatus:
      description: Use this to view the current polling status
      usage: /pollstatus <pollname>